on:
  workflow_run:
    workflows:
      - '**'
    types:
      - completed

jobs:
  actions-metrics:
    runs-on: ubuntu-latest
    env:
      ACTIONS_STEP_DEBUG: 'true'
    steps:
      - uses: yuya-takeyama/github-actions-metrics-to-datadog-action@repository-workflows-metrics
        with:
          github-token: ${{ secrets.USER_GITHUB_TOKEN_WITH_USER_SCOPE }}
          datadog-api-key: ${{ secrets.DATADOG_API_KEY }}
          enable-workflow-metrics: 'true'
          enable-billing-metrics: 'true'
          enable-repository-workflows-billing-metrics: 'true'
