name: changed-files

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  changed-files:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          echo "$CONTEXT"
        env:
          CONTEXT: ${{ toJSON(github) }}
      - uses: actions/github-script@v7
        with:
          script: |
            console.log(JSON.stringify(context, null, 2));
      - if: ${{ github.event_name == 'push' }}
        run: |
          git diff --name-only "$BEFORE" "$AFTER"
        env:
          BEFORE: ${{ github.event.before }}
          AFTER: ${{ github.event.after }}
