name: changed-files

on:
  push:

jobs:
  changed-files:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - run: |
          echo "$CONTEXT"
        env:
          CONTEXT: ${{ toJSON(github) }}
      - if: ${{ github.event_name == 'push' }}
        run: |
          git diff --name-only "$BEFORE" "$AFTER"
        env:
          BEFORE: ${{ github.event.before }}
          AFTER: ${{ github.event.after }}
