on:
  issue_comment:
    types: [created]

jobs:
  commented:
    if: startsWith(github.event.comment.body, '/hello ')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          script: |
            console.log(JSON.stringify(context));
