on:
  issue_comment:
    types: [created]

jobs:
  commented:
    if: startsWith(github.event.comment.body, '/hello ')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            console.log(JSON.stringify(context));
      - id: comment-branch
        uses: xt0rted/pull-request-comment-branch@v1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}
      - run: git rev-parse --abbrev-ref HEAD
      - run: git rev-parse --verify HEAD
