name: matrix

on:
  push

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-result.outputs.result }}
    steps:
      - uses: actions/github-script@v7
        id: set-result
        with:
          script: |
            return {config: [JSON.stringify({foo: "FOO"})]}

  run:
    needs: setup
    if: ${{ toJSON(fromJSON(needs.setup.outputs.matrix).config) != '[]' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.setup.outputs.matrix) }}
    steps:
      - run: |
          echo "Hello, ${FOO}"
          echo "Hello, ${FOO_JSON}"
        env:
          FOO: ${{ fromJSON(matrix.config).foo }}
          FOO_JSON: ${{ toJSON(fromJSON(matrix.config).foo) }}
