name: sandbox

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      logLevel:
        description: |
          Log level
          foo
        default: 'warning'
      tags:
        description: 'Test scenario tags' 

jobs:
  sandbox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git branch
      - run: echo '${{ toJSON(secrets) }}'
      - run: echo '${{ toJSON(github.event_name) }}'
      - run: echo '${{ toJSON(github.event_name == 'push') }}'
      - run: echo '${{ toJSON('foo' == 'bar') }}'
      - id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.BOT_GITHUB_APP_ID }}
          private_key: ${{ secrets.BOT_GITHUB_APP_PRIVATE_KEY }}
      - run: date > date.txt
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: date.txt
          commit_user_name: 'yuya-takeyama-test-bot[bot]'
          commit_user_email: '104966623+yuya-takeyama-test-bot[bot]@users.noreply.github.com'
          commit_author: 'yuya-takeyama-test-bot[bot] <104966623+yuya-takeyama-test-bot[bot]@users.noreply.github.com>'
