name: sandbox

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      logLevel:
        description: |
          Log level
          foo
        default: 'warning'
      tags:
        description: 'Test scenario tags' 

jobs:
  sandbox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo '${{ toJSON(secrets) }}'
      - run: echo '${{ toJSON(github.event_name) }}'
      - run: echo '${{ toJSON(github.event_name == 'push') }}'
      - run: echo '${{ toJSON('foo' == 'bar') }}'
      - id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.BOT_GITHUB_APP_ID }}
          private_key: ${{ secrets.BOT_GITHUB_APP_PRIVATE_KEY }}
      - name: Commit files
        run: |
          git config --local user.email "104966623+yuya-takeyama-test-bot[bot]@users.noreply.github.com"
          git config --local user.name "yuya-takeyama-test-bot[bot]"
          date > date.txt
          git commit -m "Add changes" -a
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ steps.generate_token.outputs.token }}
          branch: ${{ github.head_ref }}
