name: sandbox

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      logLevel:
        description: |
          Log level
          foo
        default: 'warning'
      tags:
        description: 'Test scenario tags' 

jobs:
  sandbox:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - run: echo 'github.actor = ${{ github.actor	}}'
      - run: echo "$JSON"
        env:
          JSON: ${{ toJSON(["foo", "bar", "baz"]) }}
      - run: echo '${{ toJSON(secrets) }}'
      - run: echo '${{ toJSON(github.event_name) }}'
      - run: echo '${{ toJSON(github.event_name == 'push') }}'
      - run: echo '${{ toJSON('foo' == 'foo') }}'
      - run: echo '${{ toJSON('foo' == 'bar') }}'
      - uses: actions/github-script@v6
        id: set-result
        with:
          script: |
            console.log(JSON.stringify(context));

      - uses: actions/checkout@v3
      - id: constants
        uses: ./.github/actions/constants
      - run: |
          echo '${{ steps.constants.outputs.text }}'
          echo '${{ steps.constants.outputs.json }}'
          echo '${{ fromJSON(steps.constants.outputs.json).foo }}'
          echo '${{ fromJSON(steps.constants.outputs.json).baz[2] }}'
