name: sandbox

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      logLevel:
        description: |
          Log level
          foo
        default: 'warning'
      tags:
        description: 'Test scenario tags' 

jobs:
  sandbox:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ toJSON(github) }}'
      - run: echo 'github.actor = ${{ github.actor	}}'
      - run: echo '${{ toJSON(secrets) }}'
      - run: echo '${{ toJSON(github.event_name) }}'
      - run: echo '${{ toJSON(github.event_name == 'push') }}'
      - run: echo '${{ toJSON('foo' == 'foo') }}'
      - run: echo '${{ toJSON('foo' == 'bar') }}'
      - name: JWT
        run: |
          jwt="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"
          echo "Header:"
          echo "$(echo $jwt | awk -F . '{ print $1 }' | base64 -d)"
          echo "Body:"
          echo "$(echo $jwt | awk -F . '{ print $2 }' | base64 -d)"
      - run: |
          for i in $(seq 10); do
            echo "$i"
            sleep 1
          done
      - uses: actions/github-script@v6
        id: set-result
        with:
          script: |
            console.log(JSON.stringify(context));

      - uses: actions/checkout@v3
      - id: constants
        uses: ./.github/actions/constants
      - run: |
          echo '${{ steps.constants.outputs.text }}'
          echo '${{ steps.constants.outputs.json }}'
          echo '${{ fromJSON(steps.constants.outputs.json).foo }}'
          echo '${{ fromJSON(steps.constants.outputs.json).baz[2] }}'

  matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job-param: ${{ fromJSON('[{"foo":"FOO","BAR":{},"BAZ":""}]') }}
    steps:
      - run: |
          echo "$MATRIX"
        env:
          MATRIX: ${{ toJSON(matrix) }}
      - run: |
          echo "Non-empty string is truthy"
        if: ${{ matrix.job-param.foo }}
      - run: |
          echo "Empty object is truthy"
        if: ${{ matrix.job-param.bar }}
      - run: |
          echo "Empty string is truthy"
        if: ${{ matrix.job-param.baz }}
