name: sandbox

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      logLevel:
        description: |
          Log level
          foo
        default: 'warning'
      tags:
        description: 'Test scenario tags' 

jobs:
  sandbox:
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ toJSON(secrets) }}'
      - run: echo '${{ toJSON(github.event_name) }}'
      - run: echo '${{ toJSON(github.event_name == 'push') }}'
      - run: echo '${{ toJSON('foo' == 'bar') }}'
      - id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.BOT_GITHUB_APP_ID }}
          private_key: ${{ secrets.BOT_GITHUB_APP_PRIVATE_KEY }}
      - uses: actions/github-script@v5
        id: set-result
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          script: |
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Message from bot!'
            });
            await github.request('PUT /repos/{owner}/{repo}/contents/{path}', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              path: 'test2',
              message: 'my commit message',
              content: 'bXkgbmV3IGZpbGUgY29udGVudHM='
            })
