name: sandbox

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      logLevel:
        description: |
          Log level
          foo
        default: 'warning'
      tags:
        description: 'Test scenario tags' 

jobs:
  sandbox:
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ toJSON(secrets) }}'
      - run: echo '${{ toJSON(github.event_name) }}'
      - run: echo '${{ toJSON(github.event_name == 'push') }}'
      - run: echo '${{ toJSON('foo' == 'foo') }}'
      - run: echo '${{ toJSON('foo' == 'bar') }}'
      - uses: actions/github-script@v6
        id: set-result
        with:
          script: |
            console.log(JSON.stringify(context));
