name: sandbox

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      logLevel:
        description: |
          Log level
          foo
        default: 'warning'
      tags:
        description: 'Test scenario tags' 

jobs:
  sandbox:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 30
