name: self-merge

on:
  pull_request:

  issue_comment:

jobs:
  self-merge:
    runs-on: ubuntu-latest
    steps: 
      - uses: octokit/request-action@v2.x
        id: files
        with:
          route: GET /repos/{owner}/{repo}/pulls/{pull_number}/files
          owner: ${{ github.event.pull_request.repository.owner.login }}
          repo: ${{ github.event.pull_request.repository.name }}
          pull_number: ${{ github.event.issue.number || github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: echo '${{ steps.files.outputs.result }}'
