name: workflow run

on:
  workflow_run:
    workflows:
      - '*'
    types:
      - completed

jobs:
  workflow-run:
    runs-on: ubuntu-latest
    steps:
      - uses: yuya-takeyama/github-actions-metrics-to-datadog-action@v0.1.0
        with:
          datadog-api-key: ${{ secrets.DATADOG_API_KEY }}
