name: workflow-run

on:
  workflow_run:
    workflows:
      - '**'
    branches-ignore:
      - main
    types:
      - requested

jobs:
  auto-cancel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          script: |
            console.log(JSON.stringify(context, null, 2));
      - uses: yuya-takeyama/auto-cancel-redundant-workflow-runs-action@main
        with:
          github-token: ${{ secrets.USER_GITHUB_TOKEN_WITH_USER_SCOPE }}
