name: workflow run

on:
  workflow_run:
    workflows:
      - *
    types:
      - completed

jobs:
  workflow-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          script: |
            console.log(context);
